### ISSUE TITLE
[相談部屋]相談部屋の一覧、個別ページを作成

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3503]
https://github.com/fjordllc/bootcamp/issues/2810
このIssueを分割したもの。

- 相談部屋の一覧
- 個別ページ

を作成

- ユーザーは一つの相談部屋を持っている。
- 相談部屋個別には、持ち主のユーザーと管理者だけがアクセス出来る。
- 相談部屋一覧には管理者だけがアクセス出来る。

左のナビゲーションに「相談」を追加。

- 管理者が相談をクリックすると相談部屋一覧が表示される。
- 管理者以外が相談をクリックすると自分の相談部屋個別が表示される。

**Comment by mami-inuzuka** [comment]
memo
* ユーザーができた段階で部屋ができるイメージ

**Comment by mami-inuzuka** [comment]
## task
- [ ] talksテーブルのカラムを整理
- [ ] scaffoldで必要なファイルを作成（ `rails g scaffold Talk .......`）
    - [ ] index, show, new, create
- [ ] ルーティング
    - [ ] `/users/XXXX/talk` (ポートフォリオと同じ)
- [ ] アソシエーションの設定
    - [ ] ユーザーは一つのTalkを持つ
    - [ ] ユーザーが削除されると相談部屋も削除する
- [ ] アクセス権限をつける
    - [ ] 個別ページ：持ち主のユーザーと管理者
    - [ ] 一覧：管理者のみ
- [ ] ナビゲーション
    - [ ] 相談アイコンを配置
    - [ ] リンクの分岐
        - [ ] 持ち主：自分の相談ページ
        - [ ] 管理者：一覧ページ

**Comment by mami-inuzuka** [comment]
# 確認事項
## URL/controller/viewの分け方について
* 一覧
    * URL：`/talks`
    * controller：`app/controllers/talks_controller.rb`
    * view：`app/views/talks/index.html.slim`
* 各ユーザーの相談部屋ページ
    * URL：`/users/user_id/talk`
    * controller：`app/controllers/users/talks_controller.rb`
    * view：`app/views/users/talks/show.html.slim`
* 自分の相談部屋ページ：/current_user/talk
    * URL：`/current_user/talk`
    * controller：`app/controllers/current_user/talks_controller.rb`
    * view：`app/views/current_user/talks/show.html.slim`
 ---

* 上記のように設定し、`/talks`と`/users/user_id/talk` は管理者のみアクセスできるようにする、としたが違和感がないかどうか
    * 相談部屋個別ページに関する同じviewが二つできてしまうので、自分の相談部屋ページを`/current_user/talk` とせずとも権限を分けられる方法があればそっちの方が良い？
* 各ユーザーの個別ページは一つしか存在しないので`/users/user_id/talks`ではなく`/users/user_id/talk`としたが違和感はないかどうか
    * 対応するコントローラーは`app/controllers/users/talks_controller.rb`

**Comment by mami-inuzuka** [comment]
上記の相談内容の会話内容メモ

### /talksと/users/user_id/talk は管理者のみアクセスできるようにする、としたが違和感がないかどうか
`/current_user/talk`を使用せず、全員 `/users/user_id/talk` でアクセスするようにし管理者以外でログインしている場合に自分のID以外のURLでアクセスした時は自分のIDのURLにリダイレクトするようにする

### その他
controllerやviewも全てtalksを単数系のtalkで揃える
