### ISSUE TITLE
[相談部屋]相談部屋一覧に未読、既読のタブをつけたい

### ISSUE THREAD

**Issue by machida** [fjordllc/bootcamp#3506]
![image](https://user-images.githubusercontent.com/52844263/147404050-e4b3ea92-51c0-44d0-811a-1896367b4e72.png)

**Comment by mami-inuzuka** [comment]
# TODO

- [ ] タブの設置
    - [ ] 未読：talks_path(status: 'unread')
    - [ ] 既読：talks_path
- [ ] 未読/既読の処理（コントローラー）
    - [ ] コメントがcreateされた時にreadをfalseにする
    - [ ] 相談部屋のshowアクションを呼び出した時にreadをtrueにする
- [ ] 一覧の出しわけ（Vue.js）
    - [ ]  isUnreadPageメソッドの作成（paramsにunreadがあればtrueを返す）
    - [ ] isUnreadPageの返り値がtrue/falseによってgetTalkPerPageのリクエストurlを切り替える
        - [ ] 未読：`/api/talks.json?page=${this.currentPage}&status=unread
        - [ ] 既読：`/api/talks.json?page=${this.currentPage}

**Comment by mami-inuzuka** [comment]
@machida @komagata 
こちらの仕様の確認と実装方針のご相談をさせてください。


# 仕様の確認
未読状態/既読状態の扱い方についてご相談です。

## 未読状態の扱い方
下記の仕様で大丈夫でしょうか？

* 相談部屋で新たにコメントがされたら「未読」となる
* また、その場合下記スクリーンショットのように未読マークがつく
    * <img width="925" alt="スクリーンショット 2021-12-26 18 36 22" src="https://user-images.githubusercontent.com/52844263/147404322-31bc1ea0-da2d-4578-89a8-1ca8b95fcb88.png">




## 既読状態の扱い方

既読状態の扱いとしては下記の２パターンがあるのかなと思っています。
* ①管理者の誰かが未読状態の相談部屋を確認すれば、誰がみても既読扱いとなる
* ②自分が未読状態の相談部屋を確認したとしても、既読状態となるのは自分のページ上でのみ。他の人にとっては未読のまま。

受講生からのコメントに対して管理者の誰かが確認すれば既読扱いとして良いのであれば①、管理者それぞれが必ずコメントを確認できるようにするのであれば②なのかなと思っています。

（ただ、後者で行く場合、実装が結構複雑になりそうな気がしているため実装方針についても駒形さんに相談したいです...！）
　
 
# ②で行く場合の自分なりに考えてみた実装方針
同様の未読/既読タブが実装されているのが通知一覧ページ（`/notifications`）なのでそちらを参考にしようと思っています。

通知の場合は、受け取り側一人一人が通知のデータを所持しているため個々に既読/未読の状態をもたせることが可能になっているかと思うのですが（同じ出来事に対する通知でもmachidaさんが開いた時は既読となるがkomagataさんは未読、といったようなイメージです）、今回実装しようとしている相談部屋の場合、相談部屋で発生するコメントは誰からみても同じデータが一つしか存在しないためそれ自体に既読・未読の状態を持たせることはできません。


その場合にどのようにして未読・既読の状態を管理するのかを考えていたのですが、
自分に届いた相談部屋の通知が未読/既読かによって相談部屋の未読・既読状態を出し分けることができるかな、と考えています。

ただなんとなくスマートではないような気もしているため、②で行く場合駒形さんにも実装方針をご相談したいです。

**Comment by machida** [comment]
@mami-inuzuka なるほどー、複数人が見れると既読、未読がややこしいですね。相談部屋を確認する導線としては未読、既読表示はサブ的なものになり、メインは通知になりそう、と予想しています。なので、既読、未読に複雑なものは今の時点ではまだ入れなくていいと思いました。
前者の誰かが見たら既読でひとまずお願いします🙏

**Comment by machida** [comment]
@mami-inuzuka
ごめんなさい！！
よく考えたら、未読、既読よりも、返信済みか、未返信の方が大事なことに気づきました。
こちら、仕様を変更したいです🙇‍♂️

未読、既読の機能を無しにして、
全てと、未返信のタブを付けたいです。

最後のコメントが受講生の場合は未返信、最後のコメントが管理者だった場合は返信済み、としていただきたいです🙏
仕様変更申し訳ないです🙇‍♂️

**Comment by mami-inuzuka** [comment]
@machida 
確かにそうですね！！

とんでもないです！！では全て・未返信で実装させていただきます🙆‍♀️👍

ちなみに、近しい機能として日報の全て・チェック済みのタブがあるかなと思うのですが、
今回のUIはそのタブにするのが良いか、通知一覧ページにある未読・全ての切り替えタブにするのが良いか、どちらが良さそうでしょうか？

<img width="1135" alt="スクリーンショット 2021-12-26 22 04 37" src="https://user-images.githubusercontent.com/52844263/147409041-bc935bf0-b900-4893-9f6a-d6c93ab24705.png">

<img width="1134" alt="スクリーンショット 2021-12-26 22 04 52" src="https://user-images.githubusercontent.com/52844263/147409045-7bb4d189-1c7b-41c6-898c-a024e9aa653b.png">

**Comment by machida** [comment]
@mami-inuzuka 
ありがとうございます😭
UIは前者の日報と同じパターンでお願いします🙏

**Comment by mami-inuzuka** [comment]
承知しました！！！🙆‍♀️
休日のところいろいろご確認いただいてありがとうございます🙇🏻‍♂️！！

**Comment by mami-inuzuka** [comment]
親のブランチにマージされたためクローズします。
