### ISSUE TITLE
enumをrails標準のenumに変えたい

### ISSUE THREAD

**Issue by komagata** [fjordllc/bootcamp#396]

**Comment by matt-note** [comment]
### TODO
#### Gemfile から simple_enum を削除する。
- [ ] 参考： [GemfileでインストールしたGemを削除する](https://qiita.com/sys_cat/items/16d55e7cd8a3f177863a)
  - [ ] bundle exec gem uninstall simple_enum 
  - [ ] Gemfileから削除
  - [ ] bundle update で Gemfile.lock ファイルを更新する。

**Comment by matt-note** [comment]
status_cd を status に変更する場合、以下の点を変更する。
![Screenshot from 2019-05-15 22-52-35](https://user-images.githubusercontent.com/39484102/57780948-35873880-7764-11e9-9b00-daaa2424c062.png)

**Comment by matt-note** [comment]
@komagata さん

質問です。
learnings テーブルの status_cd カラムは、status に名前を変更した方が良いでしょうか？
〇〇_cd というカラム名は、simple_enum 用のカラムだと思ったためです。
よろしくお願いします。

![Screenshot from 2019-05-15 22-41-47](https://user-images.githubusercontent.com/39484102/57780262-dc6ad500-7762-11e9-9b43-fe17761cbbd3.png)

**Comment by bluerabbit** [comment]
💭 xxx_cdってカラム最近使わないな

**Comment by komagata** [comment]
@matt-note 

https://github.com/lwe/simple_enum

simple_enum用のカラムなので変更お願いします。

**Comment by matt-note** [comment]
@komagata さん、 @bluerabbit さん

> simple_enum用のカラムなので変更お願いします。

コメントありがとうございます。
マイグレーションして、カラム名を status に変更していこうと思います。

**Comment by matt-note** [comment]
simple_enum と enum の違い

simple_enum
![Screenshot from 2019-05-16 23-06-47](https://user-images.githubusercontent.com/39484102/57860206-6a13f680-782f-11e9-97ff-eb4a995d2ef3.png)

enum
![Screenshot from 2019-05-16 23-06-59](https://user-images.githubusercontent.com/39484102/57860218-726c3180-782f-11e9-97eb-1faaf648a778.png)

**Comment by matt-note** [comment]
Learning.statuses.values_at("completed") の値

![Screenshot from 2019-05-16 23-54-13](https://user-images.githubusercontent.com/39484102/57982008-06c9d480-7a7a-11e9-8923-ff1f0166d40b.png)

**Comment by matt-note** [comment]
うまくいっていない部分です。

![Peek 2019-05-19 22-37](https://user-images.githubusercontent.com/39484102/57982932-cae93c00-7a86-11e9-85fa-18d868ff6b54.gif)

**Comment by matt-note** [comment]
simple_enum は代入で値を変更できるが、rails の enum はできない。

<small>simple_enum</small>
![Screenshot from 2019-05-22 23-13-10](https://user-images.githubusercontent.com/39484102/58181812-6d075f00-7ce7-11e9-8acf-5b9d290372d4.png)

<small>Rails の enum</small>
![Screenshot from 2019-05-22 23-08-42](https://user-images.githubusercontent.com/39484102/58181874-88726a00-7ce7-11e9-8548-55157a2009d6.png)

**Comment by komagata** [comment]
@matt-note 本番で確認したらこちらクローズお願いします。

**Comment by matt-note** [comment]
本番環境で確認できたので close します。
